namespace: spring-petclinic
imagePullPolicy: IfNotPresent

docker:
  repository: andyng195

ingress:
  name: spring-petclinic-ingress
  host: wecall.space
  userServiceName: api-gateway
  userServicePort: 8080
  adminServiceName: admin-server
  adminServicePort: 9090
  discoveryServiceName: discovery-server
  discoveryServicePort: 8761

configServerEnv: &configServerEnv
  name: CONFIG_SERVER_URL
  value: http://config-server:8888

dependOnDiscovery: &dependOnDiscovery
  name: discovery-server
  port: 8761

services:
  config-server:
    ports:
      port: 8888
      targetPort: 8888
    image:
      name: config-server

  discovery-server:
    ports:
      port: 8761
      targetPort: 8761
    image:
      name: discovery-server
    env: 
      - *configServerEnv
    dependOn: 
      name: config-server
      port: 8888

  admin-server:
    ports:
      port: 9090
      targetPort: 9090
    image:
      name: admin-server
    env: 
      - *configServerEnv
    dependOn: *dependOnDiscovery

  customers-service:
    ports:
      port: 8081
      targetPort: 8081
    image:
      name: customers-service
    env: 
      - *configServerEnv
    dependOn: *dependOnDiscovery

  visits-service:
    ports:
      port: 8082
      targetPort: 8082
    image:
      name: visits-service
    env: 
      - *configServerEnv
    dependOn: *dependOnDiscovery

  vets-service:
    ports:
      port: 8083
      targetPort: 8083
    image:
      name: vets-service
    env: 
      - *configServerEnv
    dependOn: *dependOnDiscovery

  api-gateway:
    ports:
      port: 8080
      targetPort: 8080
    image:
      name: api-gateway
    env: 
      - *configServerEnv
    dependOn: *dependOnDiscovery