apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      docker.io/andyng195/spring-petclinic-config-server
      docker.io/andyng195/spring-petclinic-discovery-server
      docker.io/andyng195/spring-petclinic-admin-server
      docker.io/andyng195/spring-petclinic-customers-service
      docker.io/andyng195/spring-petclinic-visits-service
      docker.io/andyng195/spring-petclinic-vets-service
      docker.io/andyng195/spring-petclinic-api-gateway

    # CONFIG-SERVER
    argocd-image-updater.argoproj.io/spring-petclinic-config-server.image-name: docker.io/andyng195/spring-petclinic-config-server
    argocd-image-updater.argoproj.io/spring-petclinic-config-server.helm.image-name: services.config-server.image.name
    argocd-image-updater.argoproj.io/spring-petclinic-config-server.update-strategy: latest
    argocd-image-updater.argoproj.io/spring-petclinic-config-server.allow-tags: regexp:^.*$

    # DISCOVERY-SERVER
    argocd-image-updater.argoproj.io/spring-petclinic-discovery-server.image-name: docker.io/andyng195/spring-petclinic-discovery-server
    argocd-image-updater.argoproj.io/spring-petclinic-discovery-server.helm.image-name: services.discovery-server.image.name
    argocd-image-updater.argoproj.io/spring-petclinic-discovery-server.update-strategy: latest
    argocd-image-updater.argoproj.io/spring-petclinic-discovery-server.allow-tags: regexp:^.*$

    # ADMIN-SERVER
    argocd-image-updater.argoproj.io/spring-petclinic-admin-server.image-name: docker.io/andyng195/spring-petclinic-admin-server
    argocd-image-updater.argoproj.io/spring-petclinic-admin-server.helm.image-name: services.admin-server.image.name
    argocd-image-updater.argoproj.io/spring-petclinic-admin-server.update-strategy: latest
    argocd-image-updater.argoproj.io/spring-petclinic-admin-server.allow-tags: regexp:^.*$

    # CUSTOMERS-SERVICE
    argocd-image-updater.argoproj.io/spring-petclinic-customers-service.image-name: docker.io/andyng195/spring-petclinic-customers-service
    argocd-image-updater.argoproj.io/spring-petclinic-customers-service.helm.image-name: services.customers-service.image.name
    argocd-image-updater.argoproj.io/spring-petclinic-customers-service.update-strategy: latest
    argocd-image-updater.argoproj.io/spring-petclinic-customers-service.allow-tags: regexp:^.*$

    # VISITS-SERVICE
    argocd-image-updater.argoproj.io/spring-petclinic-visits-service.image-name: docker.io/andyng195/spring-petclinic-visits-service
    argocd-image-updater.argoproj.io/spring-petclinic-visits-service.helm.image-name: services.visits-service.image.name
    argocd-image-updater.argoproj.io/spring-petclinic-visits-service.update-strategy: latest
    argocd-image-updater.argoproj.io/spring-petclinic-visits-service.allow-tags: regexp:^.*$

    # VETS-SERVICE
    argocd-image-updater.argoproj.io/spring-petclinic-vets-service.image-name: docker.io/andyng195/spring-petclinic-vets-service
    argocd-image-updater.argoproj.io/spring-petclinic-vets-service.helm.image-name: services.vets-service.image.name
    argocd-image-updater.argoproj.io/spring-petclinic-vets-service.update-strategy: latest
    argocd-image-updater.argoproj.io/spring-petclinic-vets-service.allow-tags: regexp:^.*$

    # API-GATEWAY
    argocd-image-updater.argoproj.io/spring-petclinic-api-gateway.image-name: docker.io/andyng195/spring-petclinic-api-gateway
    argocd-image-updater.argoproj.io/spring-petclinic-api-gateway.helm.image-name: services.api-gateway.image.name
    argocd-image-updater.argoproj.io/spring-petclinic-api-gateway.update-strategy: latest
    argocd-image-updater.argoproj.io/spring-petclinic-api-gateway.allow-tags: regexp:^.*$

    # Cho phép ghi ngược về Git (ví dụ vào values.yaml)
    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default
  source:
    repoURL: https://github.com/AndyNg195/argocd-devops.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml                   
        - environments/values.dev.yaml  

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true           