namespace: dev

services:
  config-server:
    image:
      tag: latest

  discovery-server:
    image:
      tag: latest

  admin-server:
    image:
      tag: f5d27e2

  customers-service:
    image:
      tag: latest

  visits-service:
    image:
      tag: latest

  vets-service:
    image:
      tag: latest

  api-gateway:
    image:
      tag: latest